global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s 
    static_configs:
      - targets: ['forestfire-prediction.up.railway.app']
    metrics_path: /metrics
    scheme: https